<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>StashScan</AssemblyName>
    <RootNamespace>StashScan</RootNamespace>
    <UseWindowsForms>false</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\TarkovHelper\Models\GameData.cs" Link="GameData.cs" />
    <Compile Include="..\..\TarkovHelper\Models\Progress.cs" Link="Progress.cs" />
    <Compile Include="..\..\TarkovHelper\Models\Need.cs" Link="Need.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

</Project>
